### ISSUE TITLE
usage of LLRP java toolkit library

### ISSUE THREAD

**Issue by rob5n** [kaansey/JAVA-LLRP-RFIDTags#2]
Hi Kaan,

Thanks for posting this useful code.

I am curious as to why you used some parts of the LLRP java toolkit, but implemented other parts yourself that are part of the toolkit?

For example, you created a Socket yourself and write to it and read from it (asynchronously), and encode and decode the data, but the Connector class in the toolkit handles quite a lot of that for you already.  Was there something in that class that wasn't satisfactory?

Cheers,
Rob

**Comment by kaansey** [comment]
Hi Rob,
I used LLRP toolkit for Reader Configuration and I don't remember really but I used socket for readThread otherwise I couldn't read the RFID data. If you can read with connector, it will be better than socket for me.

Thanks,
Kaan

**Comment by rob5n** [comment]
OK, thanks for the speedy reply!  :-)
